services:
  postgres:
    image: postgres:16-alpine
    container_name: support-backend-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: moenix/support-backend:latest
    platform: linux/amd64
    container_name: support-backend-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: support_db
      CLICKUP_API_KEY: pk_218471201_8WCJI4Q94ELQGSV72MMD4GY7RYVNM9LM
      CLICKUP_LIST_ID: 901815640131
      CLICKUP_TEAM_ID: 90181541303
      WEBHOOK_URL: https://api.alshami.me
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
