version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: support-backend-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: support-backend:latest
    container_name: support-backend-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: support_db
      CLICKUP_API_KEY: pk_
      CLICKUP_LIST_ID: 901815640131
      CLICKUP_TEAM_ID: 90181541303
      WEBHOOK_URL: https://360f-2a02-9b0-4029-4072-a5cd-7851-cde6-18a7.ngrok-free.app

volumes:
  postgres_data:
